#!/usr/bin/env Rscript

for (pkg in c(
  "docopt",
  "MALDIquant",
  "MALDIquantForeign",
  "magrittr",
  "readr",
  "purrr",
  "stringr",
  "tibble",
  "tidyr",
  "dplyr",
  "ggplot2",
  "writexl"
)) {
  suppressPackageStartupMessages(library(pkg, character.only = TRUE))
}

script_loc <-
    commandArgs(trailingOnly=FALSE) %>%
    keep(~str_detect(.x, "--file")) %>%
    str_remove("--file=") %>%
    tools::file_path_as_absolute()

project_loc <-
    script_loc %>%
    str_split(.Platform$file.sep) %>%
    unlist() %>%
    `[`(., 1:(length(.)-2)) %>%
    paste(collapse=.Platform$file.sep)

description_path <- file.path(project_loc, "DESCRIPTION")

arguments <- function() {

  parse_range <- function(range_str) {

    parsed_ranges <-
      range_str %>%
      str_split("\\s*,\\s*", simplify = TRUE) %>%
      str_split("-") %>%
      map(as.double) %>%
      map(sort)

    parsed_ranges
  }

  doc <- "maldease

  Usage:
    maldease --negative-control=<path> --output=<path> --definitions=<tsv>... [--peaks-only|--include-only=<ranges>] [options] <experiments>...
    maldease --generate-example-definitions
    maldease -v | --version
    maldease -h | --help

  Options:
    -h --help                            Print this help and exit
    -v --version                         Print program version and exit
    -n <path> --negative-control=<path>  Path to negative control MALDI results
    -o <path> --output=<path>            Output directory path
    --half-window-size=<int>             Half-window size for smoothing and peak
                                         detection [default: 20]
    --include-only=<ranges>              Consider only these mass ranges for
                                         peak reporting. Lower and upper bounds
                                         are inclusive and separated by a dash.
                                         Multiple ranges can be specified and
                                         are comma delimited,
                                         e.g.--include-only \'123-456,1000-2000\'
                                         [default: 0-Inf]
    --peaks-only                         Only report peaks within the tolerance
                                         specified by --definitions
    -d <tsv> --definitions=<tsv>         One or more paths to tab-separated
                                         defintions of target peaks
    --generate-example-definitions       Generate an example definitions file
                                         and write it to stdout
  "

  args <- docopt(doc, version = get_version())


  if (args[["--include-only"]] != "0-Inf" && args[["--peaks-only"]]) {
    cat("error: --peaks-only and --include-only are mutually exclusive\n")
    quit(save = "no", status = 1)
  }

  args[["include_only"]] <- parse_range(args[["--include-only"]])

  # Make numeric arguments the correct type
  args[["half_window_size"]] <- as.integer(args[["--half-window-size"]])

  if (args[["--generate-example-definitions"]]) {
    generate_example_definitions()
    quit(save = "no", status = 0)
  }

  args
}

main <- function() {

  args <- arguments()

  analysis_time <- Sys.time()
  analysis_params <- format_analysis_parameters(args, analysis_time)

  negative_spectra <- load_spectra(args[["negative_control"]], FALSE)

  target_definitions <- load_definitions(args[["definitions"]])

  for (experiment_path in args[["experiments"]]) {

    process_experiment(experiment_path,
                       negative_spectra,
                       target_definitions,
                       args[["half_window_size"]],
                       args[["include_only"]],
                       analysis_time,
                       analysis_params,
                       args[["output"]])
  }

  # save analysis parameters
  params_path <- file.path(args[["output"]], "params.txt")
  write_lines(analysis_params, params_path)

}

process_experiment <- function(experiment_path,
                               negative_spectra,
                               target_definitions,
                               half_window_size,
                               include_only,
                               analysis_time,
                               analysis_params,
                               output) {

  experiment_spectra <- load_spectra(experiment_path, FALSE)

  neg_sample_name <- get_sample_name(negative_spectra)
  experiment_sample_name <- get_sample_name(experiment_spectra)

  if (experiment_sample_name == neg_sample_name) {
    # Facilitate globbing experiments at the CLI and skip
    # comparing the negative control to itself
    return()
  }

  spectra <- c(experiment_spectra, negative_spectra)

  normalized_spectra <-
    preprocess_spectra(spectra, half_window_size)

  samples_avgSpectra <-
    average_technical_replicates(normalized_spectra)

  samples <- samples_avgSpectra$sample_names
  avg_spectra <- samples_avgSpectra$avg_spectra

  peaks_noise <-
    peak_detection_spectra(avg_spectra, 3, half_window_size)

  combined_peaks <- combine_peaks_and_call_positives(peaks_noise$peaks,
                                                     experiment_sample_name,
                                                     neg_sample_name,
                                                     include_only)

  spectrum_plot <- draw_plots(avg_spectra,
                              peaks_noise$peaks,
                              include_only,
                              analysis_time)

  calls <- call_positives(combined_peaks, target_definitions, neg_sample_name)

  write_output(spectrum_plot,
               combined_peaks,
               calls,
               experiment_sample_name,
               output)

}

get_version <- function() {
  version <-
    read_lines(description_path) %>%
    keep(~ grepl("Version", .x)) %>%
    str_split(": ") %>%
    unlist() %>%
    .[2] %>%
    paste("maldease", ., "\n")

  version
}

get_sample_name <- function(spectra) {
  map_chr(spectra, ~ metaData(.x)$sampleName) %>% unique()
}

load_spectra <- function(results_path, verbose) {

    spectra <-
      if (verbose) {
        MALDIquantForeign::import(results_path)
      } else {
        suppressWarnings({
          MALDIquantForeign::import(results_path)
        })
      }


    non_empty <-
      spectra %>%
      map_lgl(isEmpty) %>%
      all() %>%
      not()

    regular <-
      spectra %>%
      map_lgl(isRegular)

    if ((!non_empty) && regular) {
      cat("Input data are malformed\n")
      quit(save = "no", status = 1)
    }

    spectra
  }

load_definitions <- function(definitions_files) {

  definitions <-
    definitions_files %>% map_dfr(~ read_tsv(.x, col_types = "cdd"))

  definitions
}

calculate_ranges_from_definitions <- function(definitions) {
  # returns a string so that parse_range() can be reused

  peak_ranges_str <-
    definitions %>%
    transmute(range_str = str_glue("{mass-tolerance}-{mass+tolerance}")) %>%
    pull(range_str) %>%
    str_c(collapse = ",")

  peak_ranges_str
}

generate_example_definitions <- function() {

  # the mass tolerances are illustrative only, and
  # only intended to show a valid definition file
  #
  # you should use value appropriate to your purpose
  example_definitions <- tribble(
    ~target, ~mass, ~tolerance,
    "BoNT-A", 999,  0.6,
    "BoNT-A", 1203, 1,
    "BoNT-A", 1427, 0.5,
    "BoNT-A", 2406, 0.5
  )

  example_definitions %>% format_tsv() %>% cat()

}

preprocess_spectra <- function(spectra, half_window_size) {
  transformed_spectra <-
    spectra %>%
    # transformIntensity(method = "sqrt") %>%
    suppressWarnings({
      smoothIntensity(., method = "SavitzkyGolay",
                      halfWindowSize = half_window_size)
    })


  baseline_estimates <-
    map(transformed_spectra, function(spectrum) {
      estimateBaseline(spectrum, method = "SNIP", iterations = 100)
    })
  normalized_spectra <-
    transformed_spectra %>%
    removeBaseline(method = "SNIP", iterations = 100) %>%
    # calibrateIntensity(method = "TIC") %>%
    alignSpectra(
      halfWindowSize = half_window_size,
      SNR = 3,
      tolerance = 0.02,
      noiseMethod="SuperSmoother",
      warpingMethod = "lowess"
    )
  normalized_spectra
}

average_technical_replicates <- function(spectra) {
  samples <-
    factor(map_chr(spectra, function(x) {
      metaData(x)$sampleName
    }))

  avg_spectra <-
    averageMassSpectra(spectra, labels = samples, method = "mean")

  list(
    "sample_names" = map_chr(avg_spectra, ~ metaData(.x)$sampleName),
    "avg_spectra" = avg_spectra
  )
}

peak_detection_spectrum <-  function(spectrum,
                                     signal_to_noise_ratio,
                                     half_window_size) {
    peaks <-
      spectrum %>%
      detectPeaks(method = "SuperSmoother",
                  halfWindowSize = half_window_size,
                  SNR = signal_to_noise_ratio) %>%
      binPeaks(method="relaxed", tolerance = 0.002) %>%
      filterPeaks(minFrequency = 0.25)

    peaks
  }

peak_detection_spectra <- function(spectra,
                                   signal_to_noise_ratio,
                                   half_window_size) {
    noises <- map(spectra, ~ estimateNoise(.x, method = "SuperSmoother"))

    peaks <-
      detectPeaks(spectra,
                  noiseMethod = "SuperSmoother",
                  halfWindowSize = half_window_size,
                  SNR = signal_to_noise_ratio) %>%
      binPeaks(tolerance = 0.002) %>%
      filterPeaks(minFrequency = 0.25)

    list("noise" = noises, "peaks" = peaks)
  }

filter_mass_on_ranges <- function(mass_spec_table, incl_ranges) {

  map_dfr(incl_ranges, ~ filter(mass_spec_table, between(mass, .x[1], .x[2])))
}

combine_peaks_and_call_positives <- function(peaks,
                                             experiment_sample_name,
                                             negative_sample_name,
                                             incl_ranges) {

  neg_idx <-
    peaks %>%
    map_lgl(~ metaData(.x)$sampleName == negative_sample_name) %>%
    which()

  exp_idx <-
    peaks %>%
    map_lgl(~ metaData(.x)$sampleName == experiment_sample_name) %>%
    which()

  n <- peaks[[neg_idx]]
  e <- peaks[[exp_idx]]

  experimental_sample_name <- metaData(e)$sampleName

  merged <-
    data.frame("mass" = e@mass, e = e@intensity) %>%
    full_join(
      data.frame("mass" = n@mass, n = n@intensity),
      by = c("mass" = "mass")
    ) %>%
    arrange(mass) %>%
    mutate(
      SNR = case_when(
        is.na(e) ~ 0,
        is.na(n) ~ Inf,
        TRUE     ~ e / n
      ),
      is_positive = SNR > 3) %>%
    filter_mass_on_ranges(incl_ranges)

  colnames(merged) <- c("mass", experimental_sample_name,
                        negative_sample_name, "SNR", "is_positive")

  merged
}

draw_plots <- function(spectra, peaks, incl_ranges, analysis_time) {

  peak_tables <-
    map_dfr(
      peaks,
      ~ tibble(
        sample = .x@metaData$sampleName,
        mass = .x@mass,
        peak_intensity = .x@intensity
      )
    ) %>%
    filter_mass_on_ranges(incl_ranges)

  spectrum_tables <- imap_dfr(spectra,
                              ~ tibble(
                                sample = .y,
                                mass = .x@mass,
                                intensity = .x@intensity)
                              )

  p <-
    ggplot(spectrum_tables, aes(x = mass, y = intensity)) +
    geom_line() +
    geom_point(
      data = peak_tables,
      aes(x = mass, y = peak_intensity),
      shape = 4,
      colour = "red"
    ) +
    labs(title = analysis_time) +
    facet_wrap( ~ sample,
                ncol = 1,
                scales = "fixed") +
    theme_linedraw()

  p
}

format_analysis_parameters <- function(arg, analysis_time) {

  analysis_time_str <- paste("analysis_time", analysis_time, sep = ": ")
  cli_args <- paste(names(arg), arg, sep = ": ", collapse = "\n")

  analysis_parameters_log <- paste(analysis_time_str, cli_args, "", sep = "\n")

  analysis_parameters_log
}

call_positives <- function(intensity_table, target_definitions, negative_sample_name) {

  potential_peaks <- intensity_table %>% filter(is_positive)

  target_definitions %>%
    mutate(
      lower = mass - tolerance,
      upper = mass + tolerance,
    ) %>%
    rowwise() %>%
    mutate(
      positive = between(potential_peaks$mass, lower, upper) %>% any()
    ) %>%
    select(target, mass, positive)
}

write_output <- function(spectrum_plot,
                         intensity_table,
                         calls,
                         experiment_sample_name,
                         outpath) {

  format_outpath <- partial(file.path, outpath, experiment_sample_name)
  base_path <- format_outpath()

  if (!dir.exists(base_path)) {
    dir.create(base_path, recursive = TRUE)
  }



  plot_path <- format_outpath("mass_spectrum.png")
  table_path <- format_outpath("intensity_table.tsv")
  excel_path <- format_outpath("intensity_table.xlsx")
  calls_path <- format_outpath("calls.tsv")

  ggsave(
    filename = plot_path,
    plot = spectrum_plot,
    height = 15,
    width = 30,
    units = "cm"
  )

  write_tsv(intensity_table, table_path)
  write_tsv(calls, calls_path)
  write_xlsx(intensity_table, excel_path)

}

main()
